### ISSUE TITLE
ModuleNotFoundError: No module named 'ppt'

### ISSUE THREAD

**Issue by scstu** [sotte/pytorch_tutorial#6]
Sorry, but I got this error and don't know what should I do!! 
I installed python-pptx, but it didn't work. 
could you please tell me how to install that module? 
thank you!

**Comment by sotte** [comment]
I put some helper code into the `ppt` folder/package. You can install this package by running:
```
pip install -e .
```
Also see https://github.com/sotte/pytorch_tutorial#manual-install

Does that work for you?

**Comment by sotte** [comment]
I'll close this ticket.
Feel free to reopen it if you still have issues.

Thanks for trying out this tutorial!
